// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhawnfislqkikenxgvhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoYXduZmlzbHFraWtlbnhndmh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjYyMzIsImV4cCI6MjA2MjkwMjIzMn0.zmkAICCyx1DVs6734mdMBrtNa-wuuRgUGyUhjCezrB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);