// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cibtuvonvaomhrwjkseu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpYnR1dm9udmFvbWhyd2prc2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDU3NDIsImV4cCI6MjA2Mjg4MTc0Mn0.0qGweapsocmRLj5p_kT3YYICQJSWGS1OxXZehszQbsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);